FROM python:3.9.0a6-buster

RUN useradd -ms /bin/bash stacks

WORKDIR /stacks

COPY requirements.txt requirements.txt
RUN apt-get update -y && \
    apt-get install -y python-pip python-dev

RUN python -m venv venv

RUN venv/bin/pip install -r requirements.txt && venv/bin/pip install gunicorn

COPY app app
COPY stacks.py config.py boot.sh ./
RUN chmod +x boot.sh

ENV FLASK_APP stacks.py

RUN chown -R stacks:stacks ./
USER stacks

EXPOSE 5000
EXPOSE 5678

ENTRYPOINT ["./boot.sh"]
