apiVersion: skaffold/v2beta4
kind: Config
build:
  artifacts:
    - image: stacks-web
      context: .
deploy:
  kubectl:
    manifests:
      - ./app/kubernetes/*
      - ./db/kubernetes/*
portForward:
  - resourceType: deployment
    resourceName: stacks-svc
    port: 9000
    localPort: 9000
  - resourceType: deployment
    resourceName: stacks-web
    port: 5678
    localPort: 5678
  - resourceType: deployment
    resourceName: stacks-db
    port: 3306
    localPort: 33061
