# apiVersion: v1
# kind: Service
# metadata:
#   name: stacks-web
#   labels:
#     app: stacks-web
# spec:
#   ports:
#   - port: 8080
#     name: "stacks-web-http"
#   - port: 5678
#     name: "stacks-web-debugger"
