apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: stacks-db
  name: stacks-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stacks-db
  template:
    metadata:
      labels:
        app: stacks-db
    spec:
      containers:
        - image: mysql
          name: stacks-db
          env:
          - name: MYSQL_DATABASE
            value: stacks
          - name: MYSQL_ROOT_PASSWORD
            value: DhDQLupThgn5
          ports:
          - containerPort: 3306
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql/
      volumes:
        - name: stacks-db-pvc
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: stacks-db-pvc
