apiVersion: v1
kind: PersistentVolume
metadata:
  name: stacks-db-pv
  labels:
    type : local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: manual
  hostPath:
    path: /Users/jaydan/data/stacks-db-pv
