apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stacks-db-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: stacks-db-pv
